- name: merge defaults
  set_fact:
    clusterSpec: '{{ defaultClusterSpec | combine(clusterSpec, recursive=True) }}'
    iam_policies: '{{ default_iam_policies | combine(iam_policies, recursive=True) }}'
    iam_roles: '{{ default_iam_roles | combine(iam_roles, recursive=True) }}'
  tags:
    - always

- import_tasks: "{{ state | default('present') }}.yaml"
